title: processing-p5-convert
description: source code translator that converts Processing Java code to p5.js Javascript code
baseurl: /processing-p5-convert

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

#remote_theme:  pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme

plugins:
  - jekyll-seo-tag

